### ISSUE TITLE
 Get Workspace members?

### ISSUE THREAD

**Issue by atfernando** [MicrosoftDocs/powerbi-docs-powershell#25]
Hi,

It would be great if you could add a command to get users of a workspace.

Thanks,
Anton

**Comment by CattieCat** [comment]
Thank you for the feedback. We are planning change for PowerShell to include all API abilities, and this will be included.
Currently you can use https://docs.microsoft.com/en-us/powershell/module/microsoftpowerbimgmt.profile/invoke-powerbirestmethod?view=powerbi-ps to call https://docs.microsoft.com/en-us/rest/api/power-bi/admin/groups_getgroupsasadmin with desired filter and expand.
