### ISSUE TITLE
Please add active filter

### ISSUE THREAD

**Issue by demetrioi** [MicrosoftDocs/powerbi-docs-powershell#28]
The command does not have active/inative filter. All reports, including deleted are returned.

See comments on this link: https://github.com/Microsoft/powerbi-powershell/issues/105

**Comment by demetrioi** [comment]
Hi folks.

This is a API limitation correct?

**Comment by CattieCat** [comment]
Thank you for the feedback. We are planning change for PowerShell to include all API abilities, and this will be included.
Currently you can use https://docs.microsoft.com/en-us/powershell/module/microsoftpowerbimgmt.profile/invoke-powerbirestmethod?view=powerbi-ps to call https://docs.microsoft.com/en-us/rest/api/power-bi/admin/reports_getreportsasadmin with desired filter.
