### ISSUE TITLE
Set Dataset Image

### ISSUE THREAD

**Issue by matt40k** [MicrosoftDocs/powerbi-docs-powershell#55]
Via the Portal you can upload an image for a dataset, you should be able to do this via PowerShell.

**Comment by CattieCat** [comment]
Can you take a look if it's supported via API? https://docs.microsoft.com/en-us/rest/api/power-bi/pushdatasets/datasets_postdataset 
If so, we are planning change for PowerShell to include all API abilities, and this will probably be included.

**Comment by CattieCat** [comment]
Please follow up functionality related on https://github.com/microsoft/powerbi-powershell
