### ISSUE TITLE
Does anyone know who I could contact for an issue on the Power BI Rest API page

### ISSUE THREAD

**Issue by cvillegashak** [MicrosoftDocs/powerbi-docs-powershell#57]
The URL for usage on this page: https://docs.microsoft.com/en-us/rest/api/power-bi/dataflows/canceldataflowtransaction#code-try-0

Had two slashes before transaction causing the REST API call to fail when testing.

**Comment by CattieCat** [comment]
Thanks for feedback. I don't know the feedback channel either but I can help to get it fixed.
