### ISSUE TITLE
Issue getting the connection detail from PowerBI API

### ISSUE THREAD

**Issue by RamchanderBasker** [MicrosoftDocs/powerbi-docs-powershell#60]
When we use the command Get-PowerBIDatasource -datasetid XXXXXXX  -Scope Organization 
The connection details doesnt fetch the shared Api connection details

Name              : 
ConnectionString  : 
DatasourceType    : Sql
ConnectionDetails : Microsoft.PowerBI.Common.Api.Shared.DatasourceConnectionDetails
GatewayId         : XXXXX-XXX-XXXX-XXXX-XXXXXXXX
DatasourceId      : XXXXX-XXX-XXXXX-XXXX-XXXXXXXX

**Comment by CattieCat** [comment]
1) This repo is for public document only, please share your functionality issue on https://github.com/microsoft/powerbi-powershell.
2) Please test on https://docs.microsoft.com/en-us/rest/api/power-bi/admin/datasets-get-datasources-as-admin see what's your response and share update on repo mentioned in 1)
